name: Build and Publish Docker

on: 
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  # github.repository as nevillegrech/gigahorse-toolchain
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install Souffle
        run: sudo wget https://souffle-lang.github.io/ppa/souffle-key.public -O /usr/share/keyrings/souffle-archive-keyring.gpg
        run: echo "deb [signed-by=/usr/share/keyrings/souffle-archive-keyring.gpg] https://souffle-lang.github.io/ppa/ubuntu/ stable main" | sudo tee /etc/apt/sources.list.d/souffle.list
        run: sudo apt update
        run: sudo apt install souffle

      - name: Test Souffle
        run: souffle --version